# .bash_profile


# TODO move to its own file
# Self settings
pushd self > /dev/null
	source selfconfig
popd > /dev/null


# TODO move to its own file
# zelfconfig
pushd zelf > /dev/null
	source $HOME/zelf/zelfconfig
popd > /dev/null

# TODO move to its own file in self
addpath /usr/local/araxis
addpath /usr/local/bin

# TODO move to its own file in self
# Gools
export GOOLS_DIFFTOOL='araxis'
addpath /usr/local/gools


# TODO move to its own file in self
# Loading RVM
[[ -s $HOME/.rvm/scripts/rvm ]] && . $HOME/.rvm/scripts/rvm

