# .zshrc
# RunCom, or Run Commands

# https://apple.stackexchange.com/questions/388622/zsh-zprofile-zshrc-zlogin-what-goes-where
# https://superuser.com/questions/173165/what-does-the-rc-in-bashrc-etc-mean
# https://en.wikipedia.org/wiki/RUNCOM



echo "❇️ zshrc"


# Self settings
pushd self > /dev/null
	source selfconfig
popd > /dev/null


# Homebrew installed commands
# Usually first to take precedence
# addpath /usr/local/bin


# Gick
addpath ~/bin/gick


# Apps utilities
addpath '/Applications/Araxis Merge.app/Contents/Utilities'


# Local development binaries
addpath ~/bin


# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"


echo "☑️ zshrc"

