# .zshrc
# https://apple.stackexchange.com/questions/388622/zsh-zprofile-zshrc-zlogin-what-goes-where


echo "❇️ zshrc"


# Self settings
pushd self > /dev/null
	source selfconfig
popd > /dev/null


# Homebrew installed commands
# Usually first to take precedence
# addpath /usr/local/bin


# Gick
addpath ~/bin/gick


addpath '/Applications/Sublime Text.app/Contents/SharedSupport/bin'
addpath '/Applications/Araxis Merge.app/Contents/Utilities'


# Local development binaries
addpath ~/bin


# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"


echo "⏹ zshrc"

