#!/bin/bash

# Finds with gick a file from the modified files with a workspace status.
# With it, runs the giff command, followed with the gadd command for the
# same file.

# If run without any parameters it will pick the first available unstaged
# file.


# Checking for no options case
if [[ $# = '0' ]]; then
	fileFound=$(gick -xw "." 2> /dev/null)
else
	fileFound=$(gick -xw "$@" 2> /dev/null)
fi

if [[ $? != 0 ]]; then
	echo 'No file found' >&2
	exit 1
fi


# Checking status
stageStatus=${fileFound:0:1}
workspaceStatus=${fileFound:1:1}
fileName=${fileFound:3}

if [[ $workspaceStatus = '?' ]]; then
	echo "untracked '$fileName'"
	read -p 'Intent to add? (y) ' intentConfirm
	if [[ "$intentConfirm" != 'y' ]]; then
		echo 'Aborted' >&2
		exit 1
	fi
	
	# TODO pass as parameter to gadd once -p is supported
	echo "$fileName" | gadd -N
fi


echo 'Waiting for diff tool to return...'
giff -p "$fileName"

read -p 'Git add? (y) ' addConfirm

if [[ "$addConfirm" != 'y' ]]; then
	echo 'Aborted' >&2
	exit 1
fi

echo "$fileName" | gadd
echo
git status --short --branch

