#!/bin/bash

# Deletes all local branches except for the current one.

branchesNames=$(git branch | tr -d [:blank:] | grep -v '^*')

IFS=$'\n'
for branchName in $branchesNames; do
	git branch -d $branchName
done
unset IFS

