#!/bin/bash

# Run git mergetool using the first matching file found using gick

# TODO when supported by gick or glist, limit to files with UU status only
fileFound=$(gick "$@" 2> /dev/null)

if [[ $? -ne 0 ]]; then
	echo 'No file found' >&2
	exit 1
fi

echo "solve '$fileFound'"
git mergetool --no-prompt "$fileFound"

