#!/bin/bash

# Creates a file with random content and a specific size in megabytes
# randomfile <filename> <mbytes>

if [[ $# != 2 ]]; then
	echo 'Program must be provided a filename and number of megabytes' >&2
	echo "$(basename $0) <filename> <mbytes>" >&2
	exit 1
fi

dd if=/dev/urandom of=$1 bs=1m count=$2

