#!/bin/bash

# setback
# 
# Checks that the same files exists between two directories, and creates
# hardlinked files between the two locations to make them match.
#
# The list of directories and files to check is provided through a settings
# file. The first directory is refered as "backup", the second as "deploy".


# Without any options the program will use ~/.self_setback for settings or
# fail of the file does not exist. For each file checked a two letter 
# status is printed: first for its status in backup, the second in deploy.
# 
# MM - missing on both folders
# MF - missing in backup, present in deploy
# FM - present in backup, missing in deploy
# FF - Present in both folders and matching
# FX - Present in both folders and different


# The following options are available:
#
# -s <file> : Defines the setings file to use.
# 
# -D : Deploy the backup files into the deploy directory. For each file 
# checked in the backup directory, a hardlinked file will be created in the
# deploy directory.
# 
# -B : Backup the deploy files into the backup directory. For each file 
# checked in the deploy directory, a hardlinked file will be created in the
# backup directory.
# 
# -l : Displays the full path and filename of the files being checked. By
# default the program only prints the filename relative to the backup and
# deploy directories.



########################################
# Default values
########################################

# Options values
settingsFile="$HOME/.self_setback"
backupMode='false'
deployMode='false'
longFilename='false'

# Error codes
error_invalidOptions=1
error_missingSettingsFile=2



########################################
# Options parsing
########################################

params=$(getopt DBls: $*)
getoptStatus=$?
set -- $params

if [[ $getoptStatus != 0 ]]; then
	echo 'Invalid options' >&2
	exit $error_invalidOptions
fi

for param; do
	case "$param" in
		-s)
			# settings file
			shift
			settingsFile=$1
			shift
			;;
		-D)
			# Force copy from dotfiles to home
			deployMode='true'
			shift
			;;
		-B)
			# Update dotfiles
			backupMode='true'
			shift
			;;
		-l)
			# Update dotfiles
			longFilename='true'
			shift
			;;
		--)
			shift
			break
			;;
	esac
done

# Options validations before we start

if [[ $settingsFile = '' ]]; then
	echo 'Settings file not provided' >&2
	exit $error_missingSettingsFile
fi

if [[ ! -f $settingsFile ]]; then
	echo "Settings file not found: $settingsFile" >&2
	exit $error_missingSettingsFile
fi

if [[ $deployMode = 'true' && $backupMode = 'true' ]]; then
	echo 'Invalid options: -F and -B cannot be used simultaneously'
	exit $error_invalidOptions
fi



########################################
# Reading the settings file
########################################

backupLocation=''
deployLocation=''

# Normal stages for reading the settings file are
# backupDir -> deployDir -> files -> backupDir
# If something wrong is found "jumbBlock" is used
readStage='backupDir' # -> deployDir -> files -> backupDir

IFS=$'\n'
for line in $(cat $settingsFile); do
	
	# Cleaning and preparing the lines to be processed
	# Trimming any edge whitespace
	leading="${line%%[![:space:]]*}"
	trailing="${var##*[![:space:]]}"
	line="${line#$leading}"
	line="${line%$trailing}"
	
	firstChar=${line:0:1}
	
	# Checking for empty lines or comments
	if [[ $line = '' ]]; then
		continue
	fi
	if [[ $firstChar = '#' ]]; then
		continue
	fi
	
	# If jumping a block, we ignore everything except a block separator
	if [[ $readStage = 'jumpBlock' && ! $firstChar = '@' ]]; then
		continue
	fi
	
	# Handling block separator
	if [[ $firstChar = '@' ]]; then
		blockMessage="${line#'@'}"
		leading="${blockMessage%%[![:space:]]*}"
		blockMessage="${blockMessage#$leading}"
		echo "Block: $blockMessage"
		readStage='backupDir'
		continue
	fi
	
	# TODO jump block could be handled here, and in the case we just jump
	# everything unless we are already in a block, instead of having the
	# jumpBlock stage
	
	# Parse and check depending on the stage
	case "$readStage" in
		'backupDir')
			if [[ ${line:0:1} = '~' ]]; then
				# Fixing ~ prefix
				line="$HOME${line#'~'}"
			fi
			if [[ -d "$line" ]]; then
				backupLocation="${line%'/'}"
				readStage='deployDir'
				continue
			else
				readStage='jumpBlock'
				echo "Invalid backup location found: $line" >&2
				continue
			fi
			;;
		'deployDir')
			if [[ ${line:0:1} = '~' ]]; then
				# Fixing ~ prefix
				line="$HOME${line#'~'}"
			fi
			if [[ -d "$line" ]]; then
				deployLocation="${line%'/'}"
				readStage='files'
				continue
			else
				readStage='jumpBlock'
				echo "Invalid deploy location found: $line" >&2
				continue
			fi
			;;
		'files')
			# The rest of the logic for files is after the case statement
			;;
	esac
	
########################################
# Status logic
########################################
	
	# If we reached this place we have a file in hands
	simpleFilePath="$line"
	backupFilePath="$backupLocation/$simpleFilePath"
	deployFilePath="$deployLocation/$simpleFilePath"
	
	# Running status mode
	if [[ $deployMode = 'false' && $backupMode = 'false' ]]; then
		backupStatus='M'
		if [[ -f "$backupFilePath" ]]; then
			backupStatus='F'
		fi
		
		deployStatus='M'
		if [[ -f "$deployFilePath" ]]; then
			deployStatus='F'
		fi
		
		# If both files where found
		if [[ $deployStatus = 'F' && $deployStatus = 'F' ]]; then
			# TODO check here that if one file is a symbolic link it will still say true
			# we probably just need to check for symbolic link in the deploy location
			# otherwise the content is not really backed up to git
			if [[ ! "$backupFilePath" -ef "$deployFilePath" ]]; then
				deployStatus='X'
			fi
		fi
		
		if [[ $longFilename = 'true' ]]; then
			echo "$backupStatus$deployStatus $backupFilePath $deployFilePath"
		else
			echo "$backupStatus$deployStatus $simpleFilePath"
		fi
		
		continue
	fi
	
	
########################################
# File linking
########################################
	
	if [[ $backupMode = 'true' ]]; then
		if [[ -f "$deployFilePath" ]]; then
			if [[ $longFilename = 'true' ]]; then
				echo "B $backupFilePath"
			else
				echo "B $simpleFilePath"
			fi
			
			ln -f "$deployFilePath" "$backupFilePath"
			
		else
			if [[ $longFilename = 'true' ]]; then
				echo "M $deployFilePath"
			else
				echo "M $simpleFilePath"
			fi
		fi
		continue
	fi
	
	if [[ $deployMode = 'true' ]]; then
		if [[ -f "$backupFilePath" ]]; then
			if [[ $longFilename = 'true' ]]; then
				echo "D $deployFilePath"
			else
				echo "D $simpleFilePath"
			fi
			
			ln -f "$backupFilePath" "$deployFilePath"
			
		else
			if [[ $longFilename = 'true' ]]; then
				echo "M $backupFilePath"
			else
				echo "M $simpleFilePath"
			fi
		fi
		continue
	fi
	
done
unset IFS

