#!/bin/bash

# Using gick it opens with vim a single file in the current directory that
# matches the pattern given.

# This script uses pick, with currently resides in the gick project.

foundLine=`ls -a | pick $@ 2>/dev/null`

if [[ $? != 0 ]]; then
	echo 'No match found' >&2
	exit 1
fi

echo "opening '$foundLine'"
vim $foundLine

