#!/bin/bash

# Displays the first line string found in ~/.self_where followed

if [[ -f ~/.self_where ]]; then
	IFS=$'\n' where=($(cat ~/.self_where))
	unset IFS
else
	if [[ -t 1 ]]; then
		echo '~/.self_where file does not exist' >&2
	fi
	where=('unknown' 'unk')
fi

# --short option, only name no path
if [[ $1 = '--short' ]]; then
	printf "${where[0]}"
	exit
fi

# --ps option, for PS var
if [[ $1 = '--ps' ]]; then
	printf "${where[1]}"
	exit
fi

pwd=$(pwd)
echo "${where[0]}:$pwd"

