#!/bin/bash

read -d '' helpDoc <<"helpDoc"
NAME
    witch - open the file of a command or prints its type

SYNOPSIS
    witch [-h] [--] <command>

DESCRIPTION
    Opens a command program or script with sublime. If `<command>` is not
    a `file` its information is printed instead.

OPTIONS
    -h  Prints this help output and quits the program.
helpDoc


# Error codes
error_invalidOptions=1
error_noArguments=2
error_noType=3


# Options parsing
while getopts :h option; do
	case $option in
		'h')
			# Print help
			if [[ -t 0 ]]; then
				echo "$helpDoc" | less
			else
				echo "$helpDoc"
			fi
			exit 0
			;;
		'?')
			echo "Invalid option: -$OPTARG" >&2
			exit $error_invalidOptions
			;;
	esac
done
shift $(( OPTIND - 1 ));


commandType=$(type -t "$1")
if [[ $? != 0 ]]; then
	echo 'Command not found' >&2
	exit $error_noType
fi

# Aliases and functions seem to not exist in the subshell that is created
# for running this command. Aliases are no inherited by subcomands, or at
# least seems like they are not setup on non-interactive commands
# TODO figure out if placing aliases in bashrc would help with this?

echo "$commandType: '$1'"

case $commandType in
 	'keyword'|'builtin')
		if [[ -t 0 ]]; then
			sleep 0.5
			help "$1" | less
		else
			help "$1"
		fi
		exit 0
		;;
 	'alias')
		exit 0
		;;
	'function')
		exit 0
		;;
	'file')
		pathToFile=$(which "$1" 2>/def/null)
		subl "$pathToFile"
		exit 0
		;;
esac

