#!/bin/bash

# The two most basic ones
echo "\$@: $@"
echo "\$*: $*"

# Converting it to a list
params=($@)

# And accessing list values
echo "list[0]: ${params[0]}"
echo "list[1]: ${params[1]}"
echo "list length: ${#params[@]}"

for a; do
	echo "forloop: $a"
done

