#!/bin/bash

# try with:
# ./script uno "  dos   tres"

echo 'Printing just the parameters arrays'
echo "\$@: $@"
echo "\$*: $*"




echo
echo 'Printing each value in "$@"'
counter=1
for param in "$@"; do
	echo "\$$counter: $param"
	counter=$(($counter+1))
done

echo 'Printing each value in "$*"'
counter=1
for param in "$*"; do
	echo "\$$counter: $param"
	counter=$(($counter+1))
done




echo
echo 'Printing each value in $@'
counter=1
for param in $@; do
	echo "\$$counter: $param"
	counter=$(($counter+1))
done

echo 'Printing each value in $*'
counter=1
for param in $*; do
	echo "\$$counter: $param"
	counter=$(($counter+1))
done




echo
echo 'Printing each value in a "copy" of "$@"'
counter=1
params="$@"
for param in "$params"; do
	
	echo "\$$counter: $param"
	counter=$(($counter+1))
done

echo 'Printing each value in a "copy" of "$*"'
counter=1
params="$*"
for param in "$params"; do
	echo "\$$counter: $param"
	counter=$(($counter+1))
done




echo
echo 'Printing each value in a copy of "$@"'
counter=1
params="$@"
for param in $params; do
	
	echo "\$$counter: $param"
	counter=$(($counter+1))
done

echo 'Printing each value in a copy of "$*"'
counter=1
params="$*"
for param in $params; do
	echo "\$$counter: $param"
	counter=$(($counter+1))
done




echo
echo 'Printing each value in a "copy" of $@'
counter=1
params=$@
for param in "$params"; do
	
	echo "\$$counter: $param"
	counter=$(($counter+1))
done

echo 'Printing each value in a "copy" of $*'
counter=1
params=$*
for param in "$params"; do
	echo "\$$counter: $param"
	counter=$(($counter+1))
done




echo
echo 'Printing each value in a copy of $@'
counter=1
params=$@
for param in $params; do
	
	echo "\$$counter: $param"
	counter=$(($counter+1))
done

echo 'Printing each value in a copy of $*'
counter=1
params=$*
for param in $params; do
	echo "\$$counter: $param"
	counter=$(($counter+1))
done




echo
echo 'Printing each value in a "copy" of ("$@")'
counter=1
params=("$@")
for param in "$params"; do
	echo "\$$counter: $param"
	counter=$(($counter+1))
done

echo 'Printing each value in a "copy" of ("$*")'
counter=1
params=("$*")
for param in "$params"; do
	echo "\$$counter: $param"
	counter=$(($counter+1))
done




echo
echo 'Printing each value in a "$copy[@]" of ("$@")'
counter=1
params=("$@")
for param in "${params[@]}"; do
	echo "\$$counter: $param"
	counter=$(($counter+1))
done

echo 'Printing each value in a "$copy[@]" of ("$*")'
counter=1
params=("$*")
for param in "${params[@]}"; do
	echo "\$$counter: $param"
	counter=$(($counter+1))
done

